### ISSUE TITLE
List view exception when editing frames

### ISSUE THREAD

**Issue by simonrob** [communitymedia/mediaphone#12]
Potentially fixed in 05464f0, but adding an issue here just in case as this is the first local encounter with this longstanding bug that is seen semi-regularly on Google Play. Error:

```
    java.lang.IllegalStateException: couldn't move cursor to position 1
        at android.widget.CursorAdapter.getView(CursorAdapter.java:288)
        at ac.robinson.mediaphone.view.HorizontalListView.fillListLeft(HorizontalListView.java:362)
        at ac.robinson.mediaphone.view.HorizontalListView.fillList(HorizontalListView.java:320)
        at ac.robinson.mediaphone.view.HorizontalListView.onLayout(HorizontalListView.java:267)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.ListView.setupChild(ListView.java:2181)
        at android.widget.ListView.makeAndAddView(ListView.java:2064)
        at android.widget.ListView.fillDown(ListView.java:797)
        at android.widget.ListView.fillSpecific(ListView.java:1508)
        at android.widget.ListView.layoutChildren(ListView.java:1853)
        at android.widget.AbsListView.onLayout(AbsListView.java:2202)
        at android.view.View.layout(View.java:21927)
```

**Comment by simonrob** [comment]
No further reports since the fix linked above; marking as resolved.
